name: Public Npm

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: "@eolink"

      - name: "Publish to the npm registry"
        uses: primer/publish@3.0.0
        env:
          NPM_AUTH_TOKEN: ${{ secrets.npm_token }}
